#!groovy

// Generated by IBM TransformationAdvisor
// Tue Apr 16 16:33:59 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'mqtesterwebappwar'
    mvnCommands = '--version'
    test='false'
}